### ISSUE TITLE
Please depreciate 1.0.0 

### ISSUE THREAD

**Issue by RnbWd** [maxogden/electron-download#4]
IMO everything before this commit https://github.com/maxogden/electron-download/commit/1ac4d11ebdb2b5c7aebe654a019801a2f165f3b0 should be depcreciated on npm and maybe upgrade semver major/minor so nobody accidently uses it

**Comment by maxogden** [comment]
im not losing any sleep over it, its quite an edge case :)

**Comment by RnbWd** [comment]
:stuck_out_tongue_closed_eyes:
