### ISSUE TITLE
home-path is not consistent across drives in Windows

### ISSUE THREAD

**Issue by fritx** [maxogden/electron-download#7]
The [home-path](https://www.npmjs.com/package/home-path) doesn't add `HOMEDRIVE` to the `HOMEPATH`, so the absolute path `\\Users\\fritz.lin` isn't consistent across different Windows drives like `C:`, `D:`, etc. It isn't the actual reliable homepath either. I'd recommend using [user-home](https://www.npmjs.com/package/user-home) instead :)

Related: https://github.com/75lb/home-path/issues/2, https://github.com/egoist/nwjs/issues/4

**Comment by maxogden** [comment]
added a help wanted label in case any windows devs wanna make a PR and test it on windows

**Comment by 75lb** [comment]
fixed and released in version 1.0.1 of home-path.. please reinstall / update electron-download and try again @fritx

**Comment by fritx** [comment]
nice

**Comment by fritx** [comment]
@maxogden let's your time to bump a version ;)

**Comment by fritx** [comment]
published in 1.2.0
